# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlbertsonsAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'Dip', '7.0.1'
    pod 'Bond', '7.6.0'
    pod 'MBProgressHUD'
    pod 'ReachabilitySwift'

  target 'AlbertsonsAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
